# ### Default configuration ###
# # provide your domain here
# baseURL = "https://rematriate.netlify.app"
# languageCode = 'en-us'
# # theme
# theme = "akiagaqtaaq"
# # site title
# title = "Akiagaqtaaq"
# # disable language
# disableLanguages = []
# # google analytics
# googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# # unsafe html
# [markup.goldmark.renderer]
# unsafe = true

# ### Default Parameters ###
# [params]
# # logo is for all page
# logo = ""
# # logo white is for homepage logo, you can use colorful logo too...
# logo_white = ""
# # when logo is empty, it will shown your site title

# # OpenGraph / Twitter Card metadata
# description = "This is meta description"
# author = "Themefisher"
# image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# # customize color
# primary_color = "#02007e"
# body_color = "#f9f9f9"
# text_color = "#000000"
# text_color_dark = "#000000"
# white_color = "#ffffff"
# light_color = "#f8f9fa"

# # font family
# font_family = "lato" # Choose font family from : https://fonts.google.com/

# # contact form action
# contact_form_action = "#" # contact form works with : https://formspree.io


# ### social links ###
# [[params.social]]
# icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
# name = "Github"
# link = "#"

# ### English Language ###
# [Languages.en]
# languageName = "En"
# languageCode = "en-us"
# weight = 1
# copyright = "Copyright &copy; 2022"

# # banner
# [Languages.en.params.banner]
# title = "Rematriation Documentation"
# subtitle = "Restoring & Sharing Inuit Knowledges"
# bg_image = "images/geo_bg.png"
# placeholder = "Have a question? Just ask here or enter terms"
