name = 'Rematriate'
license = 'MIT'
licenselink = 'https://github.com/rematriation/rematriate/LICENSE'
description = 'Developed for The Rematriation Project: rematriate.net'
# The home page of the theme, where the source can be found
homepage = 'https://github.com/rematriation/rematriate'
# If you have a running demo of the theme
demosite = 'https://rematriate.net'

# Taxonomy terms
tags = ['blog', 'organization']
# features = ['some', 'awesome', 'features']

# If the theme has multiple authors
# authors = [
#   {name = 'Chris Lindgren', homepage = 'https://clndgrn.com'}
# ]

# If the theme has a single author
[author]
  name = 'Chris Lindgren'
  homepage = 'https://clndgrn.com'

